version: "3.8"

services:
  kafka-broker-01:
    image: iproduct/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
#    networks:
#      default:
#        ipv4_address: 172.28.0.2
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka-broker-01
      - BROKER_ID=1
      - BROKER_EXTERNAL_PORT=9093
      - MIN_IN_SYNC_REPLICAS=2
#      - BROKER_IP=172.28.0.2
      - BOOTSTRAP_SERVERS=localhost:9093,localhost:9094,localhost:9095
      - CONTROLLER_QUORUM_VOTERS=1@kafka-broker-01:19092,2@kafka-broker-02:19092,3@kafka-broker-03:19092


  kafka-broker-02:
    image: iproduct/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9094:9094"
#    networks:
#      default:
#        ipv4_address: 172.28.0.3
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka-broker-02
      - BROKER_ID=2
      - BROKER_EXTERNAL_PORT=9094
      - MIN_IN_SYNC_REPLICAS=2
#      - BROKER_IP=172.28.0.3
      - BOOTSTRAP_SERVERS=localhost:9093,localhost:9094,localhost:9095
      - CONTROLLER_QUORUM_VOTERS=1@kafka-broker-01:19092,2@kafka-broker-02:19092,3@kafka-broker-03:19092


  kafka-broker-03:
    image: iproduct/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9095:9095"
#    networks:
#      default:
#        ipv4_address: 172.28.0.4
    environment:
      - KAFKA_CONTAINER_HOST_NAME=kafka-broker-03
      - BROKER_ID=3
      - BROKER_EXTERNAL_PORT=9095
      - MIN_IN_SYNC_REPLICAS=2
      #      - BROKER_IP=172.28.0.4
      - BOOTSTRAP_SERVERS=kafka-broker-01:9092,kafka-broker-02:9092,kafka-broker-03:9092
      - CONTROLLER_QUORUM_VOTERS=1@kafka-broker-01:19092,2@kafka-broker-02:19092,3@kafka-broker-03:19092
      - KAFKA_CREATE_TOPICS=temperature,prices
      - KAFKA_PARTITIONS_PER_TOPIC=12
      - KAFKA_PARTITIONS_REPLICATION_FACTOR=2

#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.28.0.0/16
#          gateway: 172.28.0.1

