version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  kafka-broker-01:
    image: tiliev/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
      - "8282:8282"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka-broker-01
      - BROKER_ID=1
      - BROKER_EXTERNAL_PORT=9093
      - BOOTSTRAP_SERVERS=localhost:9093
      - CONTROLLER_QUORUM_VOTERS=1@kafka-broker-01:19092
      - KAFKA_CREATE_TOPICS=temperature,prices
      - KAFKA_PARTITIONS_PER_TOPIC=12
      - KAFKA_PARTITIONS_REPLICATION_FACTOR=1
      - KAFKA_OPTS=-javaagent:./jmx_prometheus_javaagent-0.17.0.jar=8282:./config/kafka_broker.yml

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ../prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
    - kafka-broker-01

  alertmanager:
    image: prom/alertmanager
    restart: always
    ports:
      - 19093:9093
    volumes:
      - ../alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    user: '472'
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-piechart-panel,grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ../grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus



