global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']
  - job_name: kafka
    scrape_interval: 10s
    enable_http2: false
    static_configs:
      - targets: ['host.docker.internal:8282']
        labels:
          env: "kafka-dev"
